# Site settings
title: "LiuChen"
description: "Ict. China"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "false"
resume_name:                    "LiuChen"
resume_title:                   "Institute of Computing Technology of the Chinese Academy of Sciences"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "liuchen17z[at]ict[at]ac[at]cn"

# the next two items are used for schema itemprops in _layouts/resume.html
#resume_contact_telephone:       "555-7334"
resume_contact_address:         "Haidian District, Beijing, China"

#resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>I am a PhD candidate of The Institute of Computing Technology of the Chinese Academy of Sciences.
 My research interests include software testing, distributed system, program analysis, and machine learning. 
I received my B.S. in Electronic Engineering at Tsinghua University (THU) in 2017.</p><p>
 Contact me : liuchen17z [at] ict[dot]ac[dot]cn</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "aaa"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
#resume_section_education:       true
#resume_section_projects:        true
#resume_section_skills:          true
#resume_section_recognition:     true
#resume_section_links:           true
#resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/zamerboy"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  #resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  #resume_website_url:           "http://joelglovier.com"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
